/**
 * Artifact generation for productivity agents
 */

import { getDB } from "./db";

export interface Artifact {
  id: string;
  sessionId: string;
  type: string;
  title: string;
  content: string;
  format: "markdown" | "json" | "html";
  data: Record<string, unknown>;
  createdAt: string;
}

export interface ArtifactTemplate {
  type: string;
  name: string;
  sections: string[];
}

export const artifactTemplates: Record<string, ArtifactTemplate> = {
  prd: {
    type: "prd",
    name: "Product Requirements Document",
    sections: [
      "Executive Summary",
      "Problem Statement",
      "Target Users",
      "Goals & Success Metrics",
      "Scope",
      "User Stories",
      "Functional Requirements",
      "Non-Functional Requirements",
      "Dependencies & Risks",
      "Timeline",
    ],
  },
  proposal: {
    type: "proposal",
    name: "Sales Proposal",
    sections: [
      "Executive Summary",
      "Understanding Your Needs",
      "Proposed Solution",
      "Scope of Work",
      "Timeline & Milestones",
      "Investment",
      "Why Us",
      "Next Steps",
    ],
  },
  postmortem: {
    type: "postmortem",
    name: "Incident Postmortem",
    sections: [
      "Incident Summary",
      "Timeline",
      "Impact",
      "Root Cause",
      "Contributing Factors",
      "What Went Well",
      "Action Items",
      "Lessons Learned",
    ],
  },
  roadmap: {
    type: "roadmap",
    name: "Product Roadmap",
    sections: [
      "Vision",
      "Strategic Themes",
      "Now (0-3 months)",
      "Next (3-6 months)",
      "Later (6-12 months)",
      "Decision Log",
      "Dependencies",
      "Risks & Mitigations",
    ],
  },
  sop: {
    type: "sop",
    name: "Standard Operating Procedure",
    sections: [
      "Purpose",
      "Scope",
      "Prerequisites",
      "Procedure",
      "Decision Trees",
      "Troubleshooting",
      "Definitions",
      "References",
    ],
  },
  "research-summary": {
    type: "research-summary",
    name: "Opinion Research Summary",
    sections: [
      "Research Question",
      "Methodology",
      "Key Themes",
      "Stance Map",
      "Stakeholder Profiles",
      "Areas of Consensus",
      "Points of Contention",
      "Implications",
      "Recommendations",
    ],
  },
};

/**
 * Generate an artifact from conversation data
 */
export async function generateArtifact(
  sessionId: string,
  type: string,
  title: string,
  data: Record<string, unknown>
): Promise<Artifact> {
  const db = await getDB();
  const id = crypto.randomUUID();
  const now = new Date().toISOString();

  const template = artifactTemplates[type];
  if (!template) {
    throw new Error(`Unknown artifact type: ${type}`);
  }

  // Generate markdown content from data
  const content = generateMarkdownContent(type, title, data);

  await db
    .prepare(
      `INSERT INTO artifacts (id, session_id, type, title, content, format, data, created_at)
       VALUES (?, ?, ?, ?, ?, 'markdown', ?, ?)`
    )
    .bind(id, sessionId, type, title, content, JSON.stringify(data), now)
    .run();

  // Update session with artifact reference
  await db
    .prepare("UPDATE sessions SET artifact_id = ? WHERE id = ?")
    .bind(id, sessionId)
    .run();

  return {
    id,
    sessionId,
    type,
    title,
    content,
    format: "markdown",
    data,
    createdAt: now,
  };
}

/**
 * Get artifact by ID
 */
export async function getArtifact(id: string): Promise<Artifact | null> {
  const db = await getDB();

  const result = await db
    .prepare(
      "SELECT id, session_id, type, title, content, format, data, created_at FROM artifacts WHERE id = ?"
    )
    .bind(id)
    .first<{
      id: string;
      session_id: string;
      type: string;
      title: string;
      content: string;
      format: string;
      data: string;
      created_at: string;
    }>();

  if (!result) return null;

  return {
    id: result.id,
    sessionId: result.session_id,
    type: result.type,
    title: result.title,
    content: result.content,
    format: result.format as "markdown" | "json" | "html",
    data: JSON.parse(result.data || "{}"),
    createdAt: result.created_at,
  };
}

/**
 * Generate markdown content from template and data
 */
function generateMarkdownContent(
  type: string,
  title: string,
  data: Record<string, unknown>
): string {
  const template = artifactTemplates[type];
  if (!template) return "";

  let content = `# ${title}\n\n`;
  content += `*Generated by Straits Agents ${template.name} Generator*\n\n`;
  content += `---\n\n`;

  for (const section of template.sections) {
    const key = section.toLowerCase().replace(/[^a-z0-9]/g, "_");
    const sectionData = data[key] || data[section] || "";

    content += `## ${section}\n\n`;
    if (typeof sectionData === "string") {
      content += `${sectionData}\n\n`;
    } else if (Array.isArray(sectionData)) {
      for (const item of sectionData) {
        content += `- ${item}\n`;
      }
      content += "\n";
    } else if (typeof sectionData === "object" && sectionData !== null) {
      for (const [subKey, subValue] of Object.entries(sectionData)) {
        content += `**${subKey}:** ${subValue}\n`;
      }
      content += "\n";
    } else {
      content += `*To be completed*\n\n`;
    }
  }

  content += `---\n\n`;
  content += `*Generated on ${new Date().toLocaleDateString()}*\n`;

  return content;
}
